[package]
name = "rivals-vfx-editor"
version = "3.5.0"
description = "A simple yet powerful web-based editor for batch editing color parameters in Marvel Rivals' VFX material files."
authors = ["Saturn"]
edition = "2021"
repository = "https://github.com/0xSaturno/rivals-vfx-editor.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "rivals_vfx_editor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["process", "fs", "io-util"] }
sha2 = "0.10"
hex = "0.4"
dirs = "5"
tempfile = "3"
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.21"
reqwest = { version = "0.12", features = ["json"] }
zip = { version = "2.2", default-features = false, features = ["deflate"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
